name: create_competiton
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.9.4.flutter-f9ebf21297 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_ml_vision: ^0.6.0+2

  http: ^0.12.0+1
  shared_preferences: 0.5.1+1

  firebase_messaging: ^4.0.0+1
  flare_flutter: ^1.3.2

  datetime_picker_formfield: ^0.1.8
  progress_hud: ^1.1.0
  image_picker: ^0.5.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
  - family: AbrilFatface
    fonts:
    - asset: fonts/AbrilFatface-Regular.ttf
      weight: 400

  - family: NotoSans
    fonts:
    - asset: fonts/NotoSans-Regular.ttf
      weight: 400

    - asset: fonts/NotoSans-Italic.ttf
      weight: 400
      style: italic

    - asset: fonts/NotoSans-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: fonts/OpenSans-Light.ttf
      weight: 300

    - asset: fonts/OpenSans-Light.ttf
      weight: 300
      style: italic

    - asset: fonts/OpenSans-Regular.ttf
      weight: 400

    - asset: fonts/OpenSans-Italic.ttf
      weight: 400
      style: italic

    - asset: fonts/OpenSans-SemiBold.ttf
      weight: 600

    - asset: fonts/OpenSans-SemiBoldItalic.ttf
      weight: 600
      style: italic

    - asset: fonts/OpenSans-Bold.ttf
      weight: 700

    - asset: fonts/OpenSans-BoldItalic.ttf
      weight: 700
      style: italic

    - asset: fonts/OpenSans-ExtraBold.ttf
      weight: 800

    - asset: fonts/OpenSans-ExtraBoldItalic.ttf
      weight: 800
      style: italic